### PR TITLE
Quicken CI

### PR DESCRIPTION
**Pull request by TTWNO**

### CODE REVIEW

**Comment by DataTriny** [comment]
FWIW in AccessKit CI we use [dtolnay/install](https://github.com/dtolnay/install): it is probably as fast, but definitely more readable. And it would be able to install all the binaries you need.

Also, I really don't see the benefits of running clippy for stable and beta. Why not running it on nightly only like everyone else does these days?

**Comment by TTWNO** [comment]
> Also, I really don't see the benefits of running clippy for stable and beta. Why not running it on nightly only like everyone else does these days?

I didn't know it was common to do that. I don't see any reasin why not, as long as nightly is stricter. The concern is that I don't want to be chasing down lints that end up not getting added to stable anyways.

**Comment by TTWNO** [comment]
> FWIW in AccessKit CI we use [dtolnay/install](https://github.com/dtolnay/install): it is probably as fast, but definitely more readable. And it would be able to install all the binaries you need.

I'll give this a look in my PR and see if that works just as easily. Thanks for the tip!

**Comment by DataTriny** [comment]
> I don't want to be chasing down lints that end up not getting added to stable anyways.

I think it never happened to us once, and we have set up our CI more than two years ago now. clippy probably reached some sort of maturity at this point.

**Pull request merged**
