### PR TITLE
Clippy fixes jan24

### PR DESCRIPTION
**Pull request by luukvanderduim**
Clippy and I had fun today.

### CODE REVIEW

**Comment by TTWNO** [comment]
Curious... why didn't this show up on CI before?

Were these unstable lints that just got moved into stable?

**Comment by TTWNO** [comment]
Also, good work! I always appreciate a good, simple, cleanup PR.

**Review by TTWNO — APPROVED** [review]
Much cleaner and easier to read, throughout!

**Comment by luukvanderduim** [comment]
> Curious... why didn't this show up on CI before?
> 
> Were these unstable lints that just got moved into stable?

Curious indeed.

`clippy::unnecessary_fallible_conversions` was added in 1.75.0, so this one is new in stable.
`clippy::get_first` was added in 1.63.0, which is quite a bit older.

Both are `style`-class warnings which are, strictly speaking, not wrong or unsound, but there just is a better alternative.
Maybe CI was not checking for these earlier?

I had seen the `get_first()` warning before locally, but decided against fixing it because we would end up with `get_first()` on the left hand side and `get(1)` on the right hand side - which I found an ugly imbalance. However, I realized, in these cases where we get `Value::Structure(s)` fields slice, containing the fields of an `ObjectRef`. We assert its signature first, so we are guaranteed to get a slice of two fields.  Then `get_first()` and `get_last()` are nicer.

I do not understand why CI did not pick up on `clippy::get_first` before.

**Comment by luukvanderduim** [comment]
The lint had a bug it seems, which mad [it not warn on non-primitive types](https://github.com/rust-lang/rust-clippy/issues/11594)

No longer a mystery!

**Pull request merged**
