### PR TITLE
refactor(bench): Dedup bench code and reduce variance between runs

### PR DESCRIPTION
**Pull request by luukvanderduim**
- De duplicate code: 
     Moves common code to module that is shared between tests
- Reduce variance between bench runs: 
    Generates test files with randomly generated `Messages`

### CODE REVIEW

**Comment by luukvanderduim** [comment]
CI's `cargo machete` complains about `atspi-proxies` depending on `zvariant`. 

Maybe we could try `pub(crate) use zbus/zvariant as zvariant` in the crate and no longer import it ourselves?

**Comment by TTWNO** [comment]
Great PR, Luuk! The best ones are when we remove code! Once #206 lands, I'll rebase this and should be good to go!

**Comment by TTWNO** [comment]
Also your failed checks are because I screwed up the CI, 206 also fixes those problems (I think....)

**Comment by TTWNO** [comment]
Rebased :)

**Review by TTWNO — APPROVED** [review]
LGTM!

**Pull request merged**
