### PR TITLE
Add 'bus-tree' example

### PR DESCRIPTION
**Pull request by luukvanderduim**
Addresses issue #173 

- Adds the 'bus-tree' example 

~~Also try out `static_assertions::assert_cfg!` to inform users of the appropriate features to use.
This will make rust-analyzer noisy if you don't have these set in your editor.~~

- Add `[[example]]` section in Cargo.toml, which allows us to point out, using the `required-features` list which features a user needs.
 
~~This tries to add `.vscode/settings.json` to mitigate that but if this is deemed too opinionated, just remove it.~~ 
removed, no longer needed.

### CODE REVIEW

**Comment by TTWNO** [comment]
@luukvanderduim is it possible, knowing what we know able Libreoffice Calc (2^31 children-cells), could you please add functionality for modelling "countable but almost infinite children"?

**Comment by luukvanderduim** [comment]
> @luukvanderduim is it possible, knowing what we know able Libreoffice Calc (2^31 children-cells), could you please add functionality for modelling "countable but almost infinite children"?

Yeah.. it comes at the cost of adding a call per child to get the number of children.

A reasonable number:
 - 65536 children (2^16) Children, which is max_descendants in the `Object` interface.
 
 A legal threshold:
 - 128*1024*1024 (Max Message size) / 48 (Size of an ObjectRef) = 2_708_821 children.

Or without the extra call. This will cover all stalling responses not just for (in practical terms) infinite children.

 -  A timeout (eg. 1 sec.)

**Comment by TTWNO** [comment]
> 65536 children (2^16) Children, which is max_descendants in the Object interface.

This seems good to me.

**Comment by luukvanderduim** [comment]
Last commit confirmed to make the example resilient against an 'infinite' number of children.

**Pull request merged**
